/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab9;

import org.junit.Test;
import static org.junit.Assert.*;

public class Components {
    @Test public void testAppHasAGreeting() {
        Components classUnderTest = new Components();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
