/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab9;
import java.util.Arrays;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;

public class Components {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      try
      {
        File f = new File(args[0]);
        Scanner scanner = new Scanner(f);
        int vertices = scanner.nextInt();

        int[][] adjMatrix = new int[vertices][vertices];
        while (scanner.hasNextInt()) {
          adjMatrix[scanner.nextInt()][scanner.nextInt()] = 1;
        }
        // Check adjMatrix for connected edges. If edges are not connected, increment c
        int c = 0;
        for (int i = 0; i < vertices-1; i++) {
          for (int j = 0; j < vertices-1; j++) {
            if (adjMatrix[i][j] == 1 && adjMatrix[i+1][j+1] == 0) {
              c++;
            }
          }
        }
        c++;
        System.out.println(c);

      } catch (FileNotFoundException e) {
        System.out.println("Could not find file.");
      }
    }
}
